events { worker_connections 1024; }

http {
    server {
        listen 10000;

        location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }

        location / {
            if ($http_authorization != "Bearer 2XcKOkUarnrjFJE2kwKx9f3fD7d_27Fdr4tzygXT7TUYj18AY") {
                return 401 '{"error": "Unauthorized"}';
            }
            proxy_pass http://localhost:11434;
            proxy_read_timeout 600s;
            proxy_write_timeout 600s;
        }
    }
}
